name: docln
description: "Light Novel Reader written in Flutter (for Android and iOS)"
publish_to: 'none'
version: 2024.11.22

environment:
  sdk: ^3.5.4

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.5
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  webview_flutter: ^4.7.0
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  app_settings: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  android_intent_plus: ^5.2.0
  package_info_plus: ^8.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
