name: docln
description: "Light Novel Reader written in Flutter (for Android and iOS)"
publish_to: 'none'
version: 2024.11.22

environment:
  sdk: ^3.5.4

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.5
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  webview_flutter: ^4.7.0
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  flutter_launcher_icons: ^0.14.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  android_intent_plus: ^5.2.0
  package_info_plus: ^8.1.1
  intl: ^0.19.0
  translator: ^1.0.3+1
  # Fast, lightweight key-value storage
  hive: ^2.2.3
  # Cache network requests
  dio_cache_interceptor: ^3.5.0
  # Persistent cache storage
  cached_network_image: ^3.4.1
  # Performance monitoring
  firebase_performance: ^0.10.0+10
  # Error tracking
  sentry_flutter: ^8.10.1
  # Efficient image loading and caching
  flutter_cache_manager: ^3.4.1
  # Image compression
  flutter_image_compress: ^2.3.0
  # Lazy loading images
  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
