name: docln
description: "Light Novel Reader written in Flutter (for Android and iOS)"
publish_to: 'none'
version: 2025.05.04

environment:
  sdk: ^3.7.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  sqflite: ^2.4.2
  http: ^1.3.0
  html: ^0.15.6
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.8
  webview_flutter: ^4.11.0
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^12.0.0+1
  app_settings: 5.1.1 # fix
  flutter_launcher_icons: ^0.14.3
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  android_intent_plus: ^5.2.0
  package_info_plus: ^8.1.1
  intl: ^0.19.0
  translator: ^1.0.3+1
  hive_flutter: ^1.1.0
  # Fast, lightweight key-value storage
  hive: ^2.2.3
  # Cache network requests
  dio_cache_interceptor: ^3.5.0
  # Persistent cache storage
  cached_network_image: ^3.4.1
  # Performance monitoring
  firebase_performance: ^0.10.1+5
  # Error tracking
  sentry_flutter: ^8.14.2
  # Efficient image loading and caching
  flutter_cache_manager: ^3.4.1
  # Image compression
  flutter_image_compress: ^2.3.0
  # Lazy loading images
  lazy_load_scrollview: ^1.3.0
  dio: ^5.7.0
  open_file: ^3.5.10
  shimmer: ^3.0.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  timeago: ^3.7.0
  path_provider: ^2.1.5
  wireguard_flutter: ^0.1.3
  file_picker: ^8.0.0+1 # For importing/exporting preferences
  # Encryption libraries
  encrypt: ^5.0.3
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  # SQLite encryption
  sqlcipher_flutter_libs: ^0.6.6
  # State management with BLoC pattern
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
