name: docln
description: "Light Novel Reader written in Flutter (for Android and iOS)"
publish_to: 'none'
version: 2025.08.26

environment:
  sdk: ^3.9.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  http: ^1.5.0
  html: ^0.15.6
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  webview_flutter: ^4.13.0
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.4.1
  permission_handler: ^12.0.1
  app_settings: 5.1.1 # fix
  flutter_launcher_icons: ^0.14.4
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  android_intent_plus: ^5.3.1
  package_info_plus: ^8.3.1
  intl: ^0.20.0
  translator: ^1.0.3+1
  hive_flutter: ^1.1.0
  # Fast, lightweight key-value storage
  hive: ^2.2.3
  # Cache network requests
  dio_cache_interceptor: ^4.0.3
  # Persistent cache storage
  cached_network_image: ^3.4.1
  # Error tracking
  sentry_flutter: ^9.6.0
  # Efficient image loading and caching
  flutter_cache_manager: ^3.4.1
  # Image compression
  flutter_image_compress: ^2.4.0
  # Lazy loading images
  lazy_load_scrollview: ^1.3.0
  dio: ^5.9.0
  open_file: ^3.5.10
  shimmer: ^3.0.0
  # firebase_analytics: ^11.4.5
  # firebase_crashlytics: ^4.3.5
  timeago: ^3.7.1
  path_provider: ^2.1.5
  wireguard_flutter: ^0.1.3
  file_picker: ^10.3.2 # For importing/exporting preferences
  # Encryption libraries
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  # SQLite encryption
  sqlcipher_flutter_libs: ^0.6.8
  # State management with BLoC pattern
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
