name: docln
description: "Light Novel Reader written in Flutter (for Android and iOS)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.5
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.2
  webview_flutter: ^4.0.0
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  app_settings: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  # flutter_background_service: ^5.0.5
  # flutter_background_service_android: ^6.2.2
  # workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
