// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcuX_BUb3wK_DsUjtO1EApSCPsvGwoZGc',
    appId: '1:53834218315:web:22de40ed1b2cdbc2cbc6ce',
    messagingSenderId: '53834218315',
    projectId: 'docln-fc40b',
    authDomain: 'docln-fc40b.firebaseapp.com',
    storageBucket: 'docln-fc40b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWECWvycwjEF4m7TxXLeygpCPIDzAE-8Y',
    appId: '1:53834218315:android:f07c79e1062402c1cbc6ce',
    messagingSenderId: '53834218315',
    projectId: 'docln-fc40b',
    storageBucket: 'docln-fc40b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRT4bVpEXg1dmgfsJB6ZeMClqJT3nFJM',
    appId: '1:53834218315:ios:3f0893878f9e9f2dcbc6ce',
    messagingSenderId: '53834218315',
    projectId: 'docln-fc40b',
    storageBucket: 'docln-fc40b.firebasestorage.app',
    iosBundleId: 'com.cyberdaystudios.apps.docln',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRT4bVpEXg1dmgfsJB6ZeMClqJT3nFJM',
    appId: '1:53834218315:ios:3912a2077e6f019bcbc6ce',
    messagingSenderId: '53834218315',
    projectId: 'docln-fc40b',
    storageBucket: 'docln-fc40b.firebasestorage.app',
    iosBundleId: 'com.example.docln',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcuX_BUb3wK_DsUjtO1EApSCPsvGwoZGc',
    appId: '1:53834218315:web:34e4a56f8d754bfccbc6ce',
    messagingSenderId: '53834218315',
    projectId: 'docln-fc40b',
    authDomain: 'docln-fc40b.firebaseapp.com',
    storageBucket: 'docln-fc40b.firebasestorage.app',
  );

}