// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAlSMTC6OBohxw2doIIO9Wm1twtzOQLTbc',
//     appId: '1:548956700721:web:c98a80ccdfdc85a4d6d510',
//     messagingSenderId: '548956700721',
//     projectId: 'docln-29f68',
//     authDomain: 'docln-29f68.firebaseapp.com',
//     storageBucket: 'docln-29f68.firebasestorage.app',
//     measurementId: 'G-M2SQGLT05J',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCQ7iV8jXhm5hvbwQ_rQxys-xy-VwVdTZw',
//     appId: '1:548956700721:android:8f2c03e9b04510eed6d510',
//     messagingSenderId: '548956700721',
//     projectId: 'docln-29f68',
//     storageBucket: 'docln-29f68.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBx4K4vY6LccNyeWdczLh1x0TDLvGmmlq0',
//     appId: '1:548956700721:ios:a9ea7029cb8d2367d6d510',
//     messagingSenderId: '548956700721',
//     projectId: 'docln-29f68',
//     storageBucket: 'docln-29f68.firebasestorage.app',
//     iosBundleId: 'com.example.docln',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBx4K4vY6LccNyeWdczLh1x0TDLvGmmlq0',
//     appId: '1:548956700721:ios:a9ea7029cb8d2367d6d510',
//     messagingSenderId: '548956700721',
//     projectId: 'docln-29f68',
//     storageBucket: 'docln-29f68.firebasestorage.app',
//     iosBundleId: 'com.example.docln',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAlSMTC6OBohxw2doIIO9Wm1twtzOQLTbc',
//     appId: '1:548956700721:web:23ae8ed735f39d17d6d510',
//     messagingSenderId: '548956700721',
//     projectId: 'docln-29f68',
//     authDomain: 'docln-29f68.firebaseapp.com',
//     storageBucket: 'docln-29f68.firebasestorage.app',
//     measurementId: 'G-BC2VE8GCRP',
//   );

// }
